const EMAIL_VERIFICATION_TOKEN_EXPIRY_MS = 24 * 60 * 60 * 1000;
const VERIFICATION_EMAIL_RESEND_COOLDOWN_MS = 60 * 1000;

export {
  EMAIL_VERIFICATION_TOKEN_EXPIRY_MS,
  VERIFICATION_EMAIL_RESEND_COOLDOWN_MS,
};
